// <auto-generated />
using System;
using GaiaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaiaApi.Migrations
{
    [DbContext(typeof(GaiaDbContext))]
    [Migration("20260305200612_initial_gaia_db")]
    partial class initial_gaia_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GaiaApi.Models.OperationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("FirstField")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIRST_FIELD");

                    b.Property<string>("OperationTypeCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OPERATION_TYPE_CODE");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RESULT");

                    b.Property<string>("SecondField")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SECOND_FIELD");

                    b.HasKey("Id");

                    b.ToTable("OPERATION_HISTORY", (string)null);
                });

            modelBuilder.Entity("GaiaApi.Models.OperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESC");

                    b.HasKey("Id");

                    b.ToTable("OPERATION_TYPE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
